### ISSUE TITLE
Support for the new API features :-)

### ISSUE THREAD

**Issue by andypiper** [redouane59/twitter-client#12]
Hello from Twitter Developer Relations!

First of all: Thank You, for building on our API, and for supporting our developer communities! You, and many projects like this one, are among the reasons why Twitter data is much-appreciated by developers. We historically haven't built libraries and SDKs - the communities, YOU, have done so - and I'm here to tell you how much we appreciate that, and that we know you're around!

As you already know, we are currently building a brand new API platform that (over time) will replace the current one. I would love to connect with you on any plans to add support for Twitter Developer Labs to twitter-lite! We're looking to be much more focused on proper API versioning, and are basing our specification on OpenAPI.

We would really love to continue to work with you so as you continue to help the Java community. Thank you, again!

**Comment by redouane59** [comment]
Hi @andypiper !
Thank you very for your message, of course it would be a pleasure to go further on this project and keep implementing the last twitter API features to help the community. Tell me what are the next steps !

**Comment by andypiper** [comment]
We've just announced [support for annotations](https://twittercommunity.com/t/adding-annotations-to-tweets-and-recent-search-endpoints-in-labs/135193) in the v2 Tweets and search endpoints, and there will be more to come as we migrate more endpoints to v2 over the coming weeks. Longer term, of course, we'll be graduating these APIs to a production state, and having libraries available for developers to get started quickly will be appreciated.

**Comment by redouane59** [comment]
> We've just announced [support for annotations](https://twittercommunity.com/t/adding-annotations-to-tweets-and-recent-search-endpoints-in-labs/135193) in the v2 Tweets and search endpoints, and there will be more to come as we migrate more endpoints to v2 over the coming weeks. Longer term, of course, we'll be graduating these APIs to a production state, and having libraries available for developers to get started quickly will be appreciated.

Wow it looks awesome !! I'll try to check this topic this week and study its implementation.

**Comment by redouane59** [comment]
Done @andypiper  ;)
